# Source keybinds
source-file ~/.config/tmux/keybinds.tmux

# True color settings
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"

# Set scrollback
set -g history-limit 10000

# Enable mouse
set -g mouse on

# Address vim mode switching delay
set -s escape-time 0
#
# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right'
set -g status-interval 2

#set status to top
set -g status-position top

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Fix whole word double click selection/copy
setw -g word-separators ' @"=()[]'
setw -ag word-separators "'"

# Enable clipboard sync
set -g set-clipboard on

# Enable focus events
set-option -g focus-events on

#set -g pane-border-lines heavy
#set -g pane-border-lines double
#set -g pane-border-lines single

# Yank to clipboard
set -g @yank_selection 'clipboard'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @tokyo-night-tmux_show_git 1
set -g @tokyo-night-tmux_show_wbg 0
set -g @tokyo-night-tmux_show_netspeed 0
set -g @tokyo-night-tmux_show_battery_widget 0
set -g @tokyo-night-tmux_show_music 0
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_show_hostname 0
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Initialize TMUX plugin manager (keep at bottom)
run '~/.config/tmux/plugins/tpm/tpm'
