[font]
size = 12.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"
